build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  LongMethod:
    active: false
  ComplexMethod:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 160
  WildcardImport:
    active: false
  UnusedImports:
    active: true

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9_]*'

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false
